repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    types: [file, python]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [file, python]
    args: [--max-line-length=88]
  - id: isort
    name: isort
    entry: isort
    language: python
    types: [file, python]
    args: [--profile=black]
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [file, python]
    args: [--ignore-missing-imports]
